### ISSUE TITLE
no special cookie file found

### ISSUE THREAD

**Issue by PVNFU-28** [emgram769/livechan-js#170]
I somehow got it to work on Ubuntu 20.04, but when I try to make a post it just pops the captcha over and over and on the console it says "no special cookie file found"

**Comment by pawnhearts** [comment]
https://github.com/emgram769/livechan-js/search?q=special+cookie you have to create file with a secret cookie which is used by bots(e.g. anna) to post without entering capcha and time limits between posts. On kotchan I've just moved that cookie into config.js btw I see no point in storing it in a separate file. There are a lot of changes in kotchan which are ahread on livechan but I'm too lazy to merge them back. Because some of them are kotchan-specific. On kotchan I've just disabled capcha btw. IIRC that module used for capcha there is very outdated and broken anyway.

Can you please make pull request with changes which allowed it to run on 20.04? There is some hell with packages.json - conflicts etc. I've made docker files at some point to dockerize that stuff. It worked but some stuff needs to be rewritten in  a proper way. Like ip detection for poster map is based on a netstat ))) And there are a lot of hacks like that.

I have no time, I need to fix my life. If you are willing to merge changes from kotchan here I could give you access to repo. Contact me.

**Comment by PVNFU-28** [comment]
Oh boy thanks for the response! I haven't made any changes to the source for it to work on 20.04, only changes to 20.04 to somehow adapt to livechan dependencies, and it did not work fully, honestly making a fork of livechan and just merging all kotchan upgrades dosn't seem that bad. But I am not fit for that or your offer as I don't know enough about programming and that sort of stuff.
I wish someone really got livechan to work on 20.04.
